name: Build and Deploy T3 App

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'yarn'

      - name: Install Yarn
        run: npm install -g yarn

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Run tests
        run: yarn test

  build-and-deploy:
    needs: test
    runs-on: self-hosted  # Changed to self-hosted
    
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'yarn'

      - name: Install Yarn
        run: npm install -g yarn

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build T3 App
        run: yarn build

      - name: Build Docker image
        run: docker build -t t3-trpc-app:latest .

      - name: Create app directory if not exists
        run: mkdir -p ~/workshop-ku/t3-app

      - name: Stop existing containers
        run: |
          cd ~/workshop-ku/t3-app
          docker-compose down || true

      - name: Start new containers
        run: |
          cd ~/workshop-ku/t3-app
          docker-compose up -d

      - name: Show deployment status
        run: |
          cd ~/workshop-ku/t3-app
          docker-compose ps
          docker-compose logs --tail=20

      - name: Cleanup old images
        run: docker image prune -af --filter "until=48h"